"""empty message

Revision ID: 1f62caf0312d
Revises: 1f48beaf8e22
Create Date: 2016-04-22 00:17:19.609000

"""

# revision identifiers, used by Alembic.
revision = '1f62caf0312d'
down_revision = '1f48beaf8e22'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
