"""empty message

Revision ID: 2676c569bd34
Revises: 9e436541b10
Create Date: 2016-04-22 10:37:31.840000

"""

# revision identifiers, used by Alembic.
revision = '2676c569bd34'
down_revision = '9e436541b10'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
