"""empty message

Revision ID: 30c4fa1bde4e
Revises: 511bfc7b8682
Create Date: 2016-04-18 18:11:16.381000

"""

# revision identifiers, used by Alembic.
revision = '30c4fa1bde4e'
down_revision = '511bfc7b8682'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
