"""empty message

Revision ID: 3b7e38ac01b8
Revises: da8370908a3
Create Date: 2016-04-19 17:19:17.228000

"""

# revision identifiers, used by Alembic.
revision = '3b7e38ac01b8'
down_revision = 'da8370908a3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
