"""empty message

Revision ID: 40ca7365143e
Revises: 2676c569bd34
Create Date: 2016-04-22 14:52:09.279000

"""

# revision identifiers, used by Alembic.
revision = '40ca7365143e'
down_revision = '2676c569bd34'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
