"""empty message

Revision ID: 4e7b93ee4802
Revises: 4e5cd9144c33
Create Date: 2016-04-25 18:13:43.708000

"""

# revision identifiers, used by Alembic.
revision = '4e7b93ee4802'
down_revision = '4e5cd9144c33'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
