"""empty message

Revision ID: 99b55e320a1
Revises: 4e7b93ee4802
Create Date: 2016-04-27 14:32:18.645000

"""

# revision identifiers, used by Alembic.
revision = '99b55e320a1'
down_revision = '4e7b93ee4802'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
