"""empty message

Revision ID: 9e436541b10
Revises: 1f62caf0312d
Create Date: 2016-04-22 09:59:48.756000

"""

# revision identifiers, used by Alembic.
revision = '9e436541b10'
down_revision = '1f62caf0312d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_posts_date', 'posts', ['date'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_posts_date', 'posts')
    op.drop_table('posts')
    ### end Alembic commands ###
