"""empty message

Revision ID: da8370908a3
Revises: 466f316dc50b
Create Date: 2016-04-19 17:08:12.116000

"""

# revision identifiers, used by Alembic.
revision = 'da8370908a3'
down_revision = '466f316dc50b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
